apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-replybot
  labels:
    app: gbv-replybot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gbv-replybot
  template:
    metadata:
      labels:
        app: gbv-replybot
    spec:
      containers:
      - name: gbv-replybot
        image: vlabresearch/replybot:0.0.17
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: keys
            mountPath: /usr/src/app/keys
            readOnly: true
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "chatroach-cockroachdb-public.default"
        - name: CHATBASE_PORT
          value: "26257"
        - name: REPLYBOT_EVENT_TOPIC
          value: "chat-events"
        - name: FACEBOOK_GRAPH_URL
          value: "http://gbv-facebot.default.svc.cluster.local"
      volumes:
        - name: keys
          secret:
            secretName: gbv-replybot-keys
